services:
  db:
    container_name: postgres-db-work-flow-lite
    image: postgres:latest
    environment:
      POSTGRES_USER: gusbom
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workflowlite
      PGDATA: /content/postgres
    volumes:
      - db:/content/postgres
    ports:
      - "5342:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  db: